Image labelled for garbage detection using bounding boxes in Roboflow, and the corresponding annotations used to generate a 126x126 env map

In [10]:
import numpy as np
import json
from PIL import Image

In [11]:
# Sample annotation data
annotation_data = {
    "boxes": [
        {"label": "garbage", "x": "97.73", "y": "70.72", "width": "20.26", "height": "20.24"},
        {"label": "garbage", "x": "161.57", "y": "135.38", "width": "18.95", "height": "20.56"},
        {"label": "garbage", "x": "259.07", "y": "167.03", "width": "23.93", "height": "22.87"},
        {"label": "garbage", "x": "291.81", "y": "199.24", "width": "22.43", "height": "23.28"}
    ],
    "height": 240,
    "key": "sample garbage space.jpg",
    "width": 320
}

In [12]:
# Extract dimensions
img_width = annotation_data["width"]
img_height = annotation_data["height"]

In [13]:
# Create a blank environment map
env_map = np.zeros((img_height, img_width), dtype=int)

In [14]:
# Draw the bounding boxes on the environment map
for box in annotation_data["boxes"]:
    x = int(float(box["x"]))
    y = int(float(box["y"]))
    width = int(float(box["width"]))
    height = int(float(box["height"]))
    
    # Calculate the coordinates of the bounding box
    x_min = max(0, x - width // 2)
    x_max = min(img_width, x + width // 2)
    y_min = max(0, y - height // 2)
    y_max = min(img_height, y + height // 2)
    
    # Update the environment map
    env_map[y_min:y_max, x_min:x_max] = 1

In [15]:
print(env_map)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [16]:
# Resize the environment map to 126x126
env_map_resized = Image.fromarray(env_map).resize((126, 126), Image.NEAREST)
env_map_resized_array = np.array(env_map_resized)

In [17]:
# Save the environment map as an image for visualization (optional)
env_map_resized_img = Image.fromarray((env_map_resized_array * 255).astype(np.uint8))
env_map_resized_img.save('envMap_roboflow_boundingbox.png')

In [18]:
# Output the environment map as a 128x128 matrix
print(env_map_resized_array)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [19]:
# Step 4: Save/Visualize the Environment Map
# Save as a numpy array
np.save('envMap_roboflowBoundingbox.npy', env_map)